Refactor/mapping
KonsumGandalf/awt-pj-ss24-5gmag-2 pull request #11
Opened 2024-06-18 11:57 UTC by Persists

2024-06-19 07:47 UTC, KonsumGandalf requested changes
Scheint für mich größtenteils richtig zu sein.

2024-06-19 07:47 UTC, KonsumGandalf commented on qoe-metrics-dashboard/src/app/hooks/api.ts
> +        const mappedReportList = {
hier könntest du noch den type setzten oder?

2024-06-19 07:47 UTC, KonsumGandalf commented on qoe-metrics-dashboard/src/app/hooks/qoe-report.ts
> +
Warum sind hier plötzlich typen drinnen? Könnte man die nicht auslagern?

2024-06-19 07:54 UTC, Persists commented on qoe-metrics-dashboard/src/app/hooks/qoe-report.ts
> +
Ja auf jeden Fall, das muss ich noch machen

2024-06-20 15:11 UTC, Persists commented on qoe-metrics-dashboard/src/app/hooks/qoe-report.ts
> +
Done

2024-06-20 15:11 UTC, Persists commented on qoe-metrics-dashboard/src/app/hooks/api.ts
> +        const mappedReportList = {
yes

2024-06-20 16:42 UTC, merged